---
- name: Installation des logiciels du DE01 cours CR460
  hosts: localhost
  tasks:
    - name: Installation de VSCode
      become: yes
      snap:
        name: code
        channel: latest/stable
        state: present
        classic: yes
      tags:
        - vscode

    - name: Installation de GitHub Desktop sur Ubuntu (pas de canal officiel)
      block:
        - name: Téléchargement de la clef PGP du dépôt
          become: yes
          apt_key:
            url: https://apt.packages.shiftkey.dev/gpg.key
            keyring: /usr/share/keyrings/ansible_shiftkey_repo-archive-keyring.gpg
            state: present
        - name: Ajout du dépôt GitHub Desktop
          become: yes
          apt_repository:
            repo: >-
              deb
              [arch=amd64 signed-by=/usr/share/keyrings/ansible_shiftkey_repo-archive-keyring.gpg]
              https://apt.packages.shiftkey.dev/ubuntu/
              any
              main
            filename: ansible_shiftkey_repo
            state: present
        - name: Installation de GitHub Desktop
          become: yes
          package:
            name: github-desktop
            state: latest
      tags:
        - github-desktop

    - name: Installation de GitHub CLI sur Ubuntu
      block:
        - name: Téléchargement de la clef PGP du dépôt
          become: yes
          apt_key:
            url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
            keyring: /usr/share/keyrings/ansible_githubcli_repo-archive-keyring.gpg
            state: present
        - name: Ajout du dépôt GitHub CLI
          become: yes
          apt_repository:
            repo: >-
              deb
              [arch=amd64 signed-by=/usr/share/keyrings/ansible_githubcli_repo-archive-keyring.gpg]
              https://cli.github.com/packages
              stable
              main
            filename: ansible_shiftkey_repo
            state: present
        - name: Installation de GitHub CLI
          become: yes
          package:
            name: gh
            state: latest
      tags:
        - github-cli

    - name: Installation de Terraform
      block:
        - name: Téléchargement de la clef PGP de HashiCorp
          become: yes
          apt_key:
            url: https://apt.releases.hashicorp.com/gpg
            keyring: /usr/share/keyrings/ansible_hashicorp_archive-keyring.gpg
            state: present
        - name: Ajout du dépôt de HashiCorp
          become: yes
          apt_repository:
            repo: >-
              deb
              [arch=amd64 signed-by=/usr/share/keyrings/ansible_hashicorp_archive-keyring.gpg]
              https://apt.releases.hashicorp.com
              {{ ansible_distribution_release }}
              main
            filename: ansible_hashicorp
            state: present
        - name: Installation de Terraform
          become: yes
          package:
            name: terraform
            state: latest
      tags:
        - terraform

    - name: Installation de Azure CLI
      block:
        - name: Téléchargement de la clef PGP de Microsoft
          become: yes
          apt_key:
            url: https://packages.microsoft.com/keys/microsoft.asc
            keyring: /usr/share/keyrings/ansible_microsoft_archive-keyring.gpg
            state: present
        - name: Ajout du dépôt de Azure CLI
          become: yes
          apt_repository:
            repo: >-
              deb
              [arch=amd64 signed-by=/usr/share/keyrings/ansible_microsoft_archive-keyring.gpg]
              https://packages.microsoft.com/repos/azure-cli/
              {{ ansible_distribution_release }}
              main
            filename: ansible_microsoft_azure-cli
            state: present
        - name: Installation de Azure CLI
          become: yes
          package:
            name: azure-cli
            state: latest
      tags:
        - azure-cli
